language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

env:
  - DOCUMENTER_DEBUG=true

matrix:
  allow_failures:
      - julia: nightly

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Erdos"); Pkg.test("Erdos"; coverage=true)'

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("Erdos")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("Erdos")); include(joinpath("docs", "make.jl"))'
